name: Update README File with Quote Of The Day
on:
  #[push]
  workflow_dispatch: # triggers manually
  #schedule:
  #- cron: "0 12 * * *" # triggers every midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Use Node
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install node dependencies
      run: |
        npm install --force
        npm install @actions/core axios

    - name: Run QOTD action
      uses: ./my-actions/get-quote # Uses an action in the root directory
      with:
         category: 'life'
    - name: Commit and push update
      run: |-
        git config --global user.email "Cschau0701vip@gmail.com"
        git config --global user.name "Chetan Chaudhari"
        git add -A
        git commit -m "Added QOTD from GitHub Actions"
        git push
